### ISSUE TITLE
How to `serverless invoke local`?

### ISSUE THREAD

**Issue by amaury1093** [softprops/serverless-aws-rust-multi#5]
I ran `serverless invoke local -f hello`, and got this error:

```
  Error --------------------------------------------------
 
  Error: no Rust functions found. Use 'runtime: rust' in global or function configuration to use this plugin.
 
     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information ---------------------------
     OS:                     darwin
     Node Version:           10.15.3
     Serverless Version:     1.41.1
 ```

Is it possible to invoke this function locally?

**Comment by softprops** [comment]
@amaurymartiny this should be possible as of [serverless-rust@0.3.2](https://github.com/softprops/serverless-rust/blob/master/CHANGELOG.md#-032). 

What `runtime` are you specifying in your serverless.yml file? From the error output you pasted it looks like the plugin is not about to resolve any functions using the `rust` runtime. 

I see you're using `1.41.1` which is a version ahead of what I have tested with in this repo. I'll try that and see if there wasn't a breaking change in how runtimes are declared and resolvable within plugins.

**Comment by softprops** [comment]
I think there was change in the way invokeLocal works that may have broke an interaction with the serverless rust plugin in the [1.41.0 release](https://github.com/serverless/serverless/compare/v1.40.0...v1.41.0#diff-f41c172f712b450ef245164b90bdb5d5R337) I'll do some investigation and see if I can resolve this. In the mean time you should be able to do this if you pin your serverless version to `1.40.0` instead of [^1.40.0](https://github.com/softprops/serverless-aws-rust-multi/blob/master/package.json#L3)

**Comment by softprops** [comment]
@amaurymartiny this should now be fixed in [serverless-rust plugin](https://github.com/softprops/serverless-rust/blob/master/CHANGELOG.md#-034) I'll go through these templates and update versions but the ^1.40.0 should now work as expected if you do another `npm i` to update to the latest
